spring:
  application:
    name: students #this name will be displated on the eureka interface (our discovery service)
  config:
    import: optional:configserver:http://localhost:8888 # config service url
